
======================================================================================
                  Resource Usage on 2025-01-06 21:42:03:
   Job Id:             131860378.gadi-pbs
   Project:            q90
   Exit Status:        0
   Service Units:      176.56
   NCPUs Requested:    8                      NCPUs Used: 8               
                                           CPU Time Used: 69:54:23        
   Memory Requested:   39.06GB               Memory Used: 16.6GB          
   Walltime requested: 12:00:00            Walltime Used: 09:02:23        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
